language: rust
sudo: false
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

# addons:
#   apt:
#     packages:
#     - libcurl4-openssl-dev
#     - libelf-dev
#     - libdw-dev
#     - binutils-dev # optional: only required for the --verify flag of coveralls

# before_script:
#   - pip install 'travis-cargo<0.2' --user
#   - export PATH=$HOME/.local/bin:$PATH

# script:
#   - travis-cargo build
#   - travis-cargo test
#   # - travis-cargo --only stable doc

# # after_success:
#   # - travis-cargo --only stable doc-upload
#   # - travis-cargo --only nightly coveralls --no-sudo --verify

# env:
#   global:
#     - TRAVIS_CARGO_NIGHTLY_FEATURE=""
#     # setting TRAVIS_CARGO_NIGHTLY_FEATURE globally to empty string magically
#     # avoids errors with nightly features of cargo.
