language: rust
cache: cargo
dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

env:
  global:
  - RUSTFLAGS="-C link-dead-code"

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

before_script:
- |
  cargo install cargo-kcov
  if [ ! -x $HOME/.cargo/bin/kcov ] || [ ! -f $HOME/.cargo/bin/kcov ]; then
    mkdir kcov
    cd kcov
    cargo kcov --print-install-kcov-sh | sh
    cd ${TRAVIS_BUILD_DIR}
    rm -rf kcov
  fi

script:
- |
  cargo check &&
  echo "Cargo: Passed initial compile check." &&
  cargo test --release &&
  echo "Cargo: Passed unittests." &&
  cargo kcov --release --coveralls &&
  echo "KCov: Coverage report and uploading to coveralls - done." &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "CodeCov: Uploading of data was successful!"
