[package]

name = "prophet" # other names: Pulsar
version = "0.1.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/prophet"
documentation = "https://docs.rs/prophet"
#homepage = "https://github.com/robbepop/prophet"
description = """A neural network implementation with a focus on cache-efficiency and sequential performance."""
keywords = ["deep-learning", "neural-networks", "machine-learning", "classifier"]
categories = ["science"]

[dependencies]
rand = "0.3"
num = "0.1"
ndarray = "0.8"
ndarray-rand = "0.4"
itertools = "0.5"
log = "0.3.7"

[dev-dependencies]
approx = "0.1.1"

[features]
bench = []
