[package]

name = "prophet" # other names: Pulsar
version = "0.0.2"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/prophet"
documentation = "https://docs.rs/prophet"
#homepage = "https://github.com/robbepop/prophet"
description = """
A neural network implementation with a focus on cache-efficiency and sequential performance.


"""
keywords = ["neuronal", "network", "machine", "learning"]

[dependencies]
rand = "0.3"
num = "0.1"
ndarray = "0.6"
itertools = "0.4"

[dev-dependencies]
time = "0.1"
