[package]

name    = "prophet" # other names: Pulsar
version = "0.3.0"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme  = "README.md"

keywords   = ["deep-learning", "neural-networks", "machine-learning", "classifier"]
categories = ["science"]

# homepage    = "https://github.com/robbepop/prophet"
repository    = "https://github.com/robbepop/prophet"
documentation = "https://docs.rs/prophet"
description   = """A neural network implementation with a focus on cache-efficiency and sequential performance."""

[dependencies]
rand         = "0.3.15"
num          = "0.1.37"
ndarray      = "0.9.1"
ndarray-rand = "0.5"
itertools    = "0.6"
log          = "0.3.7"
serde        = { version = "0.9", optional = true }
serde_derive = { version = "0.9", optional = true }

[dev-dependencies]
approx = "0.1.1"

[features]
run_internal_benches = []
serde_support        = ["serde", "serde_derive", "ndarray/serde"]

[badges]
travis-ci = { repository = "Robbepop/prophet" }
appveyor  = { repository = "Robbepop/prophet", branch = "master", service = "github" }
