[package]

name = "prophet" # other names: Pulsar
version = "0.0.1"
authors = ["Robin Freyler"]
license = "MIT/Apache-2.0"
readme = "README.md"
#repository = "https://github.com/robbepop/prophet"
#documentation = "https://doc.rust-lang.org/prophet"
#homepage = "https://github.com/robbepop/prophet"
description = """
A convolutional neural network implementation with a focus on cache-efficiency and performance.


"""
keywords = ["neuronal", "network", "machine", "learning"]

[dependencies]
rand = "0.3"
num = "0.1.3"
ndarray = "0.6.1"
itertools = "0.4.18"
