[package]

name = "prophet" # other names: Pulsar
version = "0.0.3"
authors = ["Robbepop"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/robbepop/prophet"
documentation = "https://docs.rs/prophet"
#homepage = "https://github.com/robbepop/prophet"
description = """A neural network implementation with a focus on cache-efficiency and sequential performance."""
keywords = ["neuronal", "network", "machine", "learning"]
categories = ["science"]

[dependencies]
rand = "0"
num = "0"
ndarray = "0"
# ndarray-rand = "0"
itertools = "0"

[dev-dependencies]
approx = "0.1.1"

[features]
bench = []
